AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  OriginAccessId:
    Description: Id of OriginAccessIdentity user user by the cloudfront distribution. Needs to be changed in the console.
    Type: String
  SSLCertificate:
    Description: ACM certificate for CloudFront
    Type: String
    Default: arn:aws:acm:us-east-1:201359054765:certificate/ea06915f-5176-40fc-9944-b4bf47c7b9a0

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: releases.gutools.co.uk
      CorsConfiguration:
        CorsRules:
        - AllowedHeaders:
          - Authorization
          MaxAge: '300'
          AllowedMethods:
          - GET
          Id: AllowHTTP
          AllowedOrigins:
          - '*'
      WebsiteConfiguration:
        IndexDocument: index.html
  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: releases.gutools.co.uk
      PolicyDocument:
        Version: 2012-10-17
        Id: S3PolicyId1
        Statement:
        - Sid: IPAllow
          Effect: Allow
          Principal: "*"
          Action:
            - s3:ListAllMyBuckets
            - s3:GetObject
          Resource: arn:aws:s3:::releases.gutools.co.uk/*
          Condition:
            IpAddress:
              aws:SourceIp:
              - 77.91.248.0/21
              - 162.213.134.128/26
        - Sid: "3"
          Effect: Allow
          Principal:
            AWS: !Sub 'arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${OriginAccessId}'
          Action: s3:GetObject
          Resource: arn:aws:s3:::releases.gutools.co.uk/index.html
  CloundFrontHTTPSEndpoint:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
        - DomainName: releases.gutools.co.uk.s3.amazonaws.com
          Id: help
          S3OriginConfig:
            OriginAccessIdentity: !Sub 'origin-access-identity/cloudfront/${OriginAccessId}'
        Enabled: 'true'
        Aliases:
        - releases.mobile-aws.gutools.co.uk
        - releases.gutools.co.uk
        DefaultCacheBehavior:
          AllowedMethods:
          - GET
          - HEAD
          TargetOriginId: help
          ForwardedValues:
            QueryString: 'true'
            Cookies:
              Forward: none
          ViewerProtocolPolicy: redirect-to-https
        ViewerCertificate:
          AcmCertificateArn: !Ref SSLCertificate
          MinimumProtocolVersion: TLSv1
          SslSupportMethod: sni-only
        DefaultRootObject: index.html
        HttpVersion: http2
  Route53DNSConfig:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: mobile-aws.gutools.co.uk.
      Name: releases.mobile-aws.gutools.co.uk.
      Type: CNAME
      TTL: '60'
      ResourceRecords:
      - !GetAtt CloundFrontHTTPSEndpoint.DomainName
